version: 1.0.{build}
branches:
  only:
  - master
nuget:
  project_feed: true
before_build:
- ps: nuget restore ./Source/CarsSystem.sln
build:
  project: ./Source/CarsSystem.sln
  publish_nuget: true
  include_nuget_references: true
  verbosity: minimal
 # notifications:
 # - provider: Email
   # to:
   # - enigmaenikov@gmail.com
   # on_build_success: true
   # on_build_failure: true
   # on_build_status_changed: true
